"""Add current_tenant_id to users table

Revision ID: add_current_tenant_id
Revises: 
Create Date: 2026-02-14 18:31:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_current_tenant_id'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('users_current_tenant_id_fkey', 'users', 'tenants', ['current_tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_current_tenant_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'current_tenant_id')
    # ### end Alembic commands ###
