"""Add current_tenant_id to users table

Revision ID: add_current_tenant_id
Revises: 
Create Date: 2026-02-14 18:31:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_current_tenant_id'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the column, don't drop any tables
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS current_tenant_id UUID REFERENCES tenants(id);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS current_tenant_id;")
    # ### end Alembic commands ###
